-- =============================================================================
-- 🌌 NATIVE HYPRLAND LUA CONFIGURATION (test-hypr-lua)
-- =============================================================================
-- Native Hyprland Lua API (hl.*) main entrypoint.

-- Disable autogenerated warning flag
hl.config({ autogenerated = false })

-- Package path configuration for modular requires
local function script_path()
    local str = debug.getinfo(2, "S").source:sub(2)
    return str:match("(.*[/\\])") or "./"
end
local base_dir = script_path()
package.path = base_dir .. "?.lua;" .. base_dir .. "?/init.lua;" .. package.path

-- Load modular configuration sections
require("config.monitors")
require("config.env")
require("config.autostart")
require("config.look")
require("config.input")
require("config.keybinds")
require("config.rules")

-- >>> hyprland-infinite-desktop-v2 (auto-installed) START
-- mainMod detected/used: "SUPER"
    hl.on("hyprland.start", function()
        hl.exec_cmd("python3 ~/scripts/infinite_desktop_core.py 1.6 > /tmp/infinite-desktop.log 2>&1")
    end)

-- Infinite desktop keybinds
hl.bind("SUPER" .. " + Z", hl.dsp.focus({ workspace = "-1" }))
hl.bind("SUPER" .. " + X", hl.dsp.focus({ workspace = "+1" }))
hl.bind("SUPER" .. " + SHIFT + Z", hl.dsp.window.move({ workspace = "-1" }))
hl.bind("SUPER" .. " + SHIFT + X", hl.dsp.window.move({ workspace = "+1" }))
hl.bind("SUPER" .. " + D", hl.dsp.exec_cmd("python3 ~/scripts/floating_tile_toggle.py"))
hl.bind("SUPER" .. " + F", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER" .. " + left", hl.dsp.exec_cmd("python3 ~/scripts/navigate_windows.py left"))
hl.bind("SUPER" .. " + ALT + left", hl.dsp.exec_cmd("python3 ~/scripts/move_window_tiled.py left"))
hl.bind("SUPER" .. " + SHIFT + left", hl.dsp.exec_cmd("python3 ~/scripts/move_window.py left"), { repeating = true })
hl.bind("SUPER" .. " + CTRL + left", hl.dsp.exec_cmd("python3 ~/scripts/resize_window.py left"), { repeating = true })
hl.bind("SUPER" .. " + right", hl.dsp.exec_cmd("python3 ~/scripts/navigate_windows.py right"))
hl.bind("SUPER" .. " + ALT + right", hl.dsp.exec_cmd("python3 ~/scripts/move_window_tiled.py right"))
hl.bind("SUPER" .. " + SHIFT + right", hl.dsp.exec_cmd("python3 ~/scripts/move_window.py right"), { repeating = true })
hl.bind("SUPER" .. " + CTRL + right", hl.dsp.exec_cmd("python3 ~/scripts/resize_window.py right"), { repeating = true })
hl.bind("SUPER" .. " + up", hl.dsp.exec_cmd("python3 ~/scripts/navigate_windows.py up"))
hl.bind("SUPER" .. " + ALT + up", hl.dsp.exec_cmd("python3 ~/scripts/move_window_tiled.py up"))
hl.bind("SUPER" .. " + SHIFT + up", hl.dsp.exec_cmd("python3 ~/scripts/move_window.py up"), { repeating = true })
hl.bind("SUPER" .. " + CTRL + up", hl.dsp.exec_cmd("python3 ~/scripts/resize_window.py up"), { repeating = true })
hl.bind("SUPER" .. " + down", hl.dsp.exec_cmd("python3 ~/scripts/navigate_windows.py down"))
hl.bind("SUPER" .. " + ALT + down", hl.dsp.exec_cmd("python3 ~/scripts/move_window_tiled.py down"))
hl.bind("SUPER" .. " + SHIFT + down", hl.dsp.exec_cmd("python3 ~/scripts/move_window.py down"), { repeating = true })
hl.bind("SUPER" .. " + CTRL + down", hl.dsp.exec_cmd("python3 ~/scripts/resize_window.py down"), { repeating = true })
-- <<< hyprland-infinite-desktop-v2 (auto-installed) END

