-- =============================================================================
-- 🌌 NATIVE HYPRLAND LUA CONFIGURATION (test-hypr-lua)
-- =============================================================================
-- Native Hyprland Lua API (hl.*) main entrypoint.

-- Disable autogenerated warning flag
hl.config({ autogenerated = false })

-- Package path configuration for modular requires
local function script_path()
    local str = debug.getinfo(2, "S").source:sub(2)
    return str:match("(.*[/\\])") or "./"
end
local base_dir = script_path()
package.path = base_dir .. "?.lua;" .. base_dir .. "?/init.lua;" .. package.path

-- Load modular configuration sections
require("config.monitors")
require("config.env")
require("config.autostart")
require("config.look")
require("config.input")
require("config.keybinds")
require("config.rules")


