#################
### AUTOSTART ###
#################

xwayland {
  force_zero_scaling = true
}

# UI Components (Disabled for Quickshell testing)
# exec-once = swaync
# exec-once = waybar
# exec-once = hyprpaper
# exec-once = ~/.config/test-hypr/scripts/wallpapers/restore-wallpaper.sh

# Quickshell Autostart (Uncomment when ready)
# exec-once = quickshell

exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = systemctl --user start hyprpolkitagent
exec-once = hypridle
# exec-once = kitty

