general {
    lock_cmd = hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Listener 1: Meredupkan layar (hanya saat tidak dicas) pada detik ke-60
listener {
    timeout = 60
    on-timeout = sh -c 'grep -q "Discharging" /sys/class/power_supply/BAT*/status && brightnessctl -s set 5'
    on-resume = sh -c 'grep -q "Discharging" /sys/class/power_supply/BAT*/status && brightnessctl -r'
}

# Listener 2: Mengunci layar (hanya saat tidak dicas) pada detik ke-120
listener {
    timeout = 120
    on-timeout = sh -c 'grep -q "Discharging" /sys/class/power_supply/BAT*/status && loginctl lock-session'
}

# (Opsional) Listener 3: Mematikan layar total (DPMS) pada detik ke-150 saat tidak dicas
# listener {
#     timeout = 150
#     on-timeout = sh -c 'grep -q "Discharging" /sys/class/power_supply/BAT*/status && hyprctl dispatch dpms off'
#     on-resume = hyprctl dispatch dpms on
# }