#Waybar
layerrule = animation slide top, match:namespace waybar

#hyprpaper
layerrule = animation fade, match:namespace hyprpaper

#Notification Control Panel
layerrule = animation slide right, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-control-center
layerrule = ignore_alpha 0.6, match:namespace swaync-control-center

#Notification
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.6, match:namespace swaync-notification-window

#Wlogout
layerrule = blur on, match:namespace logout_dialog
layerrule = ignore_alpha 0.5, match:namespace logout_dialog

# layerrule = blur on, match:namespace swaync
# layerrule = ignore_alpha 0, match:namespace swaync