# Variables
$inFocusOpacity = 1
$notInFocusOpacity = 0.7

# --- STYLE: ACTION FIRST (Format Paling Aman) ---

# 1. Suppress Event
# Gunakan regex class langsung tanpa 'match:'
windowrule = match:class .*, suppress_event maximize

# 2. No Focus
# WAJIB: Pakai underscore (no_focus), pakai angka 1, dan SPASI setelah titik dua
windowrule = match:class ^$ title: ^$ xwayland: 1 floating: 1 fullscreen: 0 pinned: 0, no_focus 1

# 3. Opacity & Tiling
# WAJIB: Spasi antara 'class:' dan nama class-nya
# windowrule = match:class ^(kitty)$, opacity 1
windowrule = match:class ^(kitty)$, opacity 0.80 0.50
windowrule = match:class ^(Lunar Client.*)$, fullscreen 1
windowrule = match:class ^(Lunar Client.*)$, tile 1

# 4. Browser Opacity
windowrule = match:class ^(firefox|brave|librewolf|qutebrowser|zen-browser)$, opacity $inFocusOpacity $notInFocusOpacity

# 5. Aplikasi Lain (Filter Title)
# Gunakan spasi setelah 'title:'
windowrule = match:class ^.*(Spotify).*$, opacity $inFocusOpacity $notInFocusOpacity
windowrule = match:title ^.*(Discord).*$, opacity $inFocusOpacity $notInFocusOpacity
windowrule = match:title ^.*(Telegram).*$, opacity $inFocusOpacity $notInFocusOpacity
windowrule = match:title ^.*(Code).*$, opacity $inFocusOpacity $notInFocusOpacity
windowrule = match:title ^.*(Thunar|nemo).*$, opacity $inFocusOpacity $notInFocusOpacity
